version: '3.9'

services:

  gate-simulator:
    build: .
    image: gate-simulator:1.0
    ports:
      - 9999:9999

  mysql-db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass