name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql_db:
        image: mysql:latest
        ports:
          - 3307:3306
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: pass
        options: >-
          --health-cmd "mysqladmin -u app -p'pass' ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build gate-simulator image
        run: docker build -t gate-simulator:latest .

      - name: Run gate-simulator container
        run: docker run -d -p 9999:9999 gate-simulator:latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: start SUT with connection to MySQL DB
        run: java -jar ./artifacts/aqa-shop.jar &

      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true