name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: pass
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build gate-simulator image
        run: docker build -t gate-simulator:latest .

      - name: Run gate-simulator container
        run: docker run -d -p 9999:9999 gate-simulator:latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: start SUT with connection to PostgreSQL DB
        run: java -jar ./artifacts/aqa-shop.jar --spring.datasource.url=jdbc:postgresql://localhost:5432/app &

      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true -Ddb.url=jdbc:postgresql://localhost:5432/app